[project]
name = "audio-utilities"
version = "0.1.0"
requires-python = ">=3.11,<3.13"
dependencies = [
    "librosa>=0.11.0",
    "numpy>=2.0.2,<2.1.0",
    "soundfile>=0.13.1",
    "numba>=0.59.0",
    "torch==2.8.0+cu128",
    "torchaudio==2.8.0+cu128",
    "torchvision==0.23.0+cu128",
    "onnxruntime-gpu>=1.23.2",
    "huggingface-hub",
    "hf_transfer>=0.1.0",
    "faster-whisper>=1.0.0",
    "torchfcpe>=0.0.4",
    "speechbrain>=1.0.1",
    "pyloudnorm>=0.1.1",
    "pesq",
    "pystoi",
    "yamlargparse",
    "torchinfo",
    "torch-complex",
    "typeguard",
    "rotary-embedding-torch",
    "python_speech_features",
    "pydub",
    "audio-separator>=0.40.0",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = false

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchaudio = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }

[tool.uv]
prerelease = "allow"


